### PR TITLE
Export Faction Characteristics

### LINKED ISSUE #11: Export faction characteristics from Squad SDK
Right now, SquadLayerList doesn't have any faction characteristics (such as "Extra ATGM", "Extra Intel" etc). These should be exported together with the rest of the faction data.

A list of all faction characteristics is available in the FactionCharacteristicTable at DataTable'/Game/Settings/FactionSetups/FactionCharacteristicTable.FactionCharacteristicTable'. Inside each characteristic is a Row Name and a DisplayText describing the characteristic.

Example:

Row Name: HAB+
DisplayText: +1 extra HAB avaliable per FOB

Each faction has a list of characteristics defined at "Characteristics", with each element including the above Data Table and the Row Name. The Characteristics Table can be accessed the same way as the Vehicles table.

### PR DESCRIPTION
**Pull request by sorenjohanson**
closes #11

### CODE REVIEW

**Comment by fantinodavide** [comment]
thank you @sorenjohanson! I'll try to fix my sdk to test this asap

**Comment by fantinodavide** [comment]
@sorenjohanson could you please merge main into your branch and resolve the conflicts? I'll then merge this into main. Also, a workflow should now generate the lists with the legacy format

**Comment by fantinodavide** [comment]
@sorenjohanson do you have an update on the development of this PR? If you can't resolve the conflict I can delete the layers.json file, and just merge the changes made to the exporter.py file! Let me know what you think about that!

**Comment by sorenjohanson** [comment]
Sorry, work was kinda packed the last few weeks. I'm working on regenerating the list now, I'll push an update soon that hopefully resolves the merge conflict.

**Review by fantinodavide — APPROVED** [review]
Thank you @sorenjohanson awesome work!

**Pull request merged**
